title        = "Orangebomb"
baseurl      = "http://blog.orangebomb.org"
languageCode = "ja-jp"

[author]
  Name = "keita_kawamoto"
  Bio  = [
    "UI, Graphic Designer.「わからない」をなくす研究。"
  ]

[permalinks]
  post = "/blog/:year/:month/:day/:filename/"

[params]
  Twitter = "keita_kawamoto"
  GitHub  = "keitakawamoto"
